services:
  db: 
    image: mysql:8.0.31
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: todoappdb
      MYSQL_ROOT_PASSWORD: test_root
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
  api:
    image: myapiforcompose:latest
    ports:
      - 80:80

